version: 2.1

executors:
  ubuntu1404:
    machine:
      image: circleci/classic:latest
  ubuntu1604:
    machine:
      image: ubuntu-1604:201903-01

commands:
  docker_build_debian10:
    steps:
      - run: docker build -t vagrant:debian10 https://github.com/leighmcculloch/vagrant-docker-image.git#:debian10
      - run: docker tag vagrant:debian10 vagrant:latest
  docker_build_centos7:
    steps:
      - run: docker build -t vagrant:centos7 https://github.com/leighmcculloch/vagrant-docker-image.git#:centos7
      - run: docker tag vagrant:centos7 vagrant:latest
  test:
    steps:
      - run: bundle install --path vendor/bundle
      - run: bundle exec vagrant up
      - run: bundle exec vagrant ssh -c 'lscpu && docker run'

jobs:
  pc1:
    executor: ubuntu1404
    steps:
      - docker_build_debian10
      - checkout
      - test
  pc2:
    executor: ubuntu1404
    steps:
      - docker_build_centos7
      - checkout
      - test
  pc3:
    executor: ubuntu1604
    steps:
      - docker_build_debian10
      - checkout
      - test
  pc4:
    executor: ubuntu1604
    steps:
      - docker_build_centos7
      - checkout
      - test

workflows:
  version: 2
  test:
    jobs:
      - pc1
      - pc2
      - pc3
      - pc4
